# Generated by Django 5.0.1 on 2025-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('turnstile_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
